run:
  go: "1.23"
  timeout: 1m
  issues-exit-code: 1
  tests: true

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - musttag
    - varnamelen
    - nlreturn
    - gomnd
    - execinquery
    - exportloopref
    - wrapcheck
    - gci
    - tagliatelle
    - godot
    - depguard
    - gofumpt
    - err113
    - exhaustruct
    - wsl
    
linters-settings:
  lll:
    line-length: 140
